spring:
  application:
    name: meeting-room-management
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, circuitbreakers