package com.yasarbilgi.visitormeetingmanagment.permission.entity;

public enum PermissionCategory {
    COMPANY_MANAGEMENT,
    USER_MANAGEMENT,
    ROLE_MANAGEMENT,
    PERMISSION_MANAGEMENT,
    JOB_TITLE_MANAGEMENT,
    ROOM_MANAGEMENT,
    FEATURE_MANAGEMENT,
    RESERVATION_MANAGEMENT,
    VISITOR_MANAGEMENT,
    DASHBOARD,
    REPORTING,
    AUDIT,
    NOTIFICATION
}