INSERT INTO role_templates (name, description, created_at, updated_at, version, active)
VALUES
('Sistem Yöneticisi', 'Sistemdeki tüm yönetim yetkilerine sahip en üst düzey rol', now(), now(), 0, true),
('İnsan Kaynakları', 'Şirket yapısını, personeli, odaları, rezervasyonları ve ziyaretçileri yöneten operasyonel rol', now(), now(), 0, true),
('Tesis Yöneticisi', 'Odaların fiziksel/teknik durumundan ve envanterinden sorumlu rol', now(), now(), 0, true),
('Takım Lideri', 'Kendi ekibinin rezervasyon ve ziyaretçi süreçlerini yöneten ara yönetici rolü', now(), now(), 0, true),
('Departman Asistanı', 'Departman yöneticileri adına takvim ve toplantı organizasyonu yapan rol', now(), now(), 0, true),
('Güvenlik', 'Resepsiyon/lobide ziyaretçi giriş-çıkış süreçlerini yöneten rol', now(), now(), 0, true),
('Çalışan', 'Sadece kendi verilerini gören standart son kullanıcı rolü', now(), now(), 0, true);

INSERT INTO role_template_permissions (role_template_id, permission_id)

-- Sistem Yöneticisi: tüm izinler
SELECT rt.id, p.id FROM role_templates rt CROSS JOIN permissions p
WHERE rt.name = 'Sistem Yöneticisi'

UNION ALL

-- İnsan Kaynakları
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'İnsan Kaynakları' AND p.code IN (
    'COMPANY_VIEW', 'COMPANY_UPDATE',
    'USER_CREATE', 'USER_VIEW', 'USER_VIEW_ALL', 'USER_UPDATE', 'USER_DELETE', 'USER_DEACTIVATE',
    'USER_ACTIVATE', 'USER_MANAGE', 'USER_ASSIGN_ROLE', 'USER_REVOKE_ROLE', 'USER_ASSIGN_JOB_TITLE',
    'ROLE_VIEW',
    'PERMISSION_VIEW',
    'JOB_TITLE_CREATE', 'JOB_TITLE_VIEW', 'JOB_TITLE_UPDATE', 'JOB_TITLE_DELETE', 'JOB_TITLE_DEACTIVATE',
    'JOB_TITLE_ACTIVATE', 'JOB_TITLE_MANAGE', 'JOB_TITLE_ASSIGN_DEFAULT_ROLE', 'JOB_TITLE_REMOVE_DEFAULT_ROLE',
    'ROOM_CREATE', 'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY', 'ROOM_UPDATE', 'ROOM_DELETE', 'ROOM_DEACTIVATE',
    'ROOM_ACTIVATE', 'ROOM_MANAGE_FEATURES',
    'FEATURE_CREATE', 'FEATURE_VIEW', 'FEATURE_UPDATE', 'FEATURE_DELETE',
    'RESERVATION_CREATE', 'RESERVATION_VIEW_OWN', 'RESERVATION_VIEW_ALL', 'RESERVATION_UPDATE_OWN',
    'RESERVATION_UPDATE_ALL', 'RESERVATION_CANCEL_OWN', 'RESERVATION_CANCEL_ALL', 'RESERVATION_APPROVE',
    'RESERVATION_REJECT', 'RESERVATION_VIEW_DETAILS', 'RESERVATION_FILTER_BY_DATE', 'RESERVATION_FILTER_BY_ROOM',
    'VISITOR_CREATE', 'VISITOR_VIEW', 'VISITOR_CHECK_IN', 'VISITOR_CHECK_OUT', 'VISITOR_ASSIGN_CARD',
    'VISITOR_VIEW_HISTORY', 'VISITOR_CANCEL',
    'DASHBOARD_VIEW',
    'REPORT_VIEW_DAILY_VISITORS', 'REPORT_VIEW_ACTIVE_VISITORS', 'REPORT_VIEW_UNCHECKED_OUT_VISITORS',
    'REPORT_VIEW_ROOM_USAGE', 'REPORT_VIEW_RESERVATION_STATS', 'REPORT_VIEW_CANCELLATION_STATS', 'REPORT_EXPORT_EXCEL',
    'NOTIFICATION_VIEW', 'NOTIFICATION_MANAGE_SETTINGS'
)

UNION ALL

-- Tesis Yöneticisi
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'Tesis Yöneticisi' AND p.code IN (
    'COMPANY_VIEW',
    'USER_VIEW', 'USER_VIEW_ALL',
    'PERMISSION_VIEW',
    'ROOM_CREATE', 'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY', 'ROOM_UPDATE', 'ROOM_DELETE', 'ROOM_DEACTIVATE',
    'ROOM_ACTIVATE', 'ROOM_MANAGE_FEATURES',
    'FEATURE_CREATE', 'FEATURE_VIEW', 'FEATURE_UPDATE', 'FEATURE_DELETE',
    'RESERVATION_VIEW_ALL', 'RESERVATION_VIEW_DETAILS', 'RESERVATION_CANCEL_ALL', 'RESERVATION_FILTER_BY_DATE',
    'RESERVATION_FILTER_BY_ROOM',
    'DASHBOARD_VIEW',
    'REPORT_VIEW_ROOM_USAGE', 'REPORT_EXPORT_EXCEL',
    'NOTIFICATION_VIEW'
)

UNION ALL

-- Takım Lideri
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'Takım Lideri' AND p.code IN (
    'COMPANY_VIEW',
    'USER_VIEW', 'USER_VIEW_ALL',
    'JOB_TITLE_VIEW',
    'PERMISSION_VIEW',
    'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY',
    'FEATURE_VIEW',
    'RESERVATION_CREATE', 'RESERVATION_VIEW_OWN', 'RESERVATION_VIEW_ALL', 'RESERVATION_UPDATE_OWN',
    'RESERVATION_CANCEL_OWN', 'RESERVATION_VIEW_DETAILS', 'RESERVATION_FILTER_BY_DATE', 'RESERVATION_FILTER_BY_ROOM',
    'VISITOR_CREATE', 'VISITOR_VIEW', 'VISITOR_VIEW_HISTORY', 'VISITOR_CANCEL',
    'DASHBOARD_VIEW',
    'NOTIFICATION_VIEW'
)

UNION ALL

-- Departman Asistanı
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'Departman Asistanı' AND p.code IN (
    'COMPANY_VIEW',
    'USER_VIEW', 'USER_VIEW_ALL',
    'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY',
    'FEATURE_VIEW',
    'RESERVATION_CREATE', 'RESERVATION_VIEW_OWN', 'RESERVATION_VIEW_ALL', 'RESERVATION_UPDATE_OWN',
    'RESERVATION_UPDATE_ALL', 'RESERVATION_CANCEL_OWN', 'RESERVATION_CANCEL_ALL', 'RESERVATION_VIEW_DETAILS',
    'RESERVATION_FILTER_BY_DATE', 'RESERVATION_FILTER_BY_ROOM',
    'VISITOR_CREATE', 'VISITOR_VIEW', 'VISITOR_VIEW_HISTORY', 'VISITOR_CANCEL',
    'DASHBOARD_VIEW',
    'NOTIFICATION_VIEW'
)

UNION ALL

-- Güvenlik
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'Güvenlik' AND p.code IN (
    'USER_VIEW',
    'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY',
    'RESERVATION_FILTER_BY_DATE', 'RESERVATION_FILTER_BY_ROOM',
    'VISITOR_CREATE', 'VISITOR_VIEW', 'VISITOR_CHECK_IN', 'VISITOR_CHECK_OUT', 'VISITOR_ASSIGN_CARD',
    'VISITOR_VIEW_HISTORY', 'VISITOR_CANCEL',
    'DASHBOARD_VIEW',
    'REPORT_VIEW_DAILY_VISITORS', 'REPORT_VIEW_ACTIVE_VISITORS', 'REPORT_VIEW_UNCHECKED_OUT_VISITORS',
    'NOTIFICATION_VIEW'
)

UNION ALL

-- Çalışan
SELECT rt.id, p.id FROM role_templates rt, permissions p
WHERE rt.name = 'Çalışan' AND p.code IN (
    'COMPANY_VIEW',
    'USER_VIEW',
    'ROOM_VIEW', 'ROOM_VIEW_AVAILABILITY',
    'FEATURE_VIEW',
    'RESERVATION_CREATE', 'RESERVATION_VIEW_OWN', 'RESERVATION_UPDATE_OWN', 'RESERVATION_CANCEL_OWN',
    'RESERVATION_FILTER_BY_DATE', 'RESERVATION_FILTER_BY_ROOM',
    'VISITOR_CREATE', 'VISITOR_VIEW', 'VISITOR_CANCEL',
    'DASHBOARD_VIEW',
    'NOTIFICATION_VIEW'
);
