INSERT INTO permissions (code, name, description, category, is_system_permission, display_order, created_at, updated_at,
                         version, active)
VALUES
-- Company Management
('COMPANY_VIEW', 'Şirket Görüntüleme', 'Şirket bilgilerini görüntüleme yetkisi', 'COMPANY_MANAGEMENT', true, 1, now(),
 now(), 0, true),
('COMPANY_UPDATE', 'Şirket Güncelleme', 'Şirket bilgilerini güncelleme yetkisi', 'COMPANY_MANAGEMENT', true, 2, now(),
 now(), 0, true),
('COMPANY_MANAGE_SETTINGS', 'Şirket Ayarlarını Yönetme', 'Şirket ayarlarını yönetme yetkisi', 'COMPANY_MANAGEMENT',
 true, 3, now(), now(), 0, true),

-- User Management
('USER_CREATE', 'Kullanıcı Oluşturma', 'Yeni kullanıcı oluşturma yetkisi', 'USER_MANAGEMENT', true, 10, now(), now(), 0,
 true),
('USER_VIEW', 'Kullanıcı Görüntüleme', 'Kendi bilgilerini görüntüleme yetkisi', 'USER_MANAGEMENT', true, 11, now(),
 now(), 0, true),
('USER_VIEW_ALL', 'Tüm Kullanıcıları Görüntüleme', 'Şirketteki tüm kullanıcıları görüntüleme yetkisi',
 'USER_MANAGEMENT', true, 12, now(), now(), 0, true),
('USER_UPDATE', 'Kullanıcı Güncelleme', 'Kullanıcı bilgilerini güncelleme yetkisi', 'USER_MANAGEMENT', true, 13, now(),
 now(), 0, true),
('USER_DELETE', 'Kullanıcı Silme', 'Kullanıcı silme yetkisi', 'USER_MANAGEMENT', true, 14, now(), now(), 0, true),
('USER_DEACTIVATE', 'Kullanıcı Pasifleştirme', 'Kullanıcıyı pasif hale getirme yetkisi', 'USER_MANAGEMENT', true, 15,
 now(), now(), 0, true),
('USER_ACTIVATE', 'Kullanıcı Aktifleştirme', 'Kullanıcıyı aktif hale getirme yetkisi', 'USER_MANAGEMENT', true, 16,
 now(), now(), 0, true),
('USER_MANAGE', 'Kullanıcı Yönetimi', 'Genel kullanıcı yönetim yetkisi', 'USER_MANAGEMENT', true, 17, now(), now(), 0,
 true),
('USER_ASSIGN_ROLE', 'Rol Atama', 'Kullanıcıya rol atama yetkisi', 'USER_MANAGEMENT', true, 18, now(), now(), 0, true),
('USER_REVOKE_ROLE', 'Rol Geri Alma', 'Kullanıcıdan rol geri alma yetkisi', 'USER_MANAGEMENT', true, 19, now(), now(),
 0, true),
('USER_ASSIGN_JOB_TITLE', 'Unvan Atama', 'Kullanıcıya unvan atama yetkisi', 'USER_MANAGEMENT', true, 20, now(), now(),
 0, true),
('USER_GRANT_PERMISSION_OVERRIDE', 'Özel İzin Ekleme', 'Kullanıcıya özel izin ekleme yetkisi', 'USER_MANAGEMENT', true,
 21, now(), now(), 0, true),
('USER_REVOKE_PERMISSION_OVERRIDE', 'Özel İzin Geri Alma', 'Kullanıcıdan özel izin geri alma yetkisi',
 'USER_MANAGEMENT', true, 22, now(), now(), 0, true),
('USER_TRANSFER_OWNERSHIP', 'Sahiplik Devri', 'Şirket sahipliğini devretme yetkisi', 'USER_MANAGEMENT', true, 23, now(),
 now(), 0, true),

-- Role Management
('ROLE_CREATE', 'Rol Oluşturma', 'Yeni rol oluşturma yetkisi', 'ROLE_MANAGEMENT', true, 30, now(), now(), 0, true),
('ROLE_VIEW', 'Rol Görüntüleme', 'Rolleri görüntüleme yetkisi', 'ROLE_MANAGEMENT', true, 31, now(), now(), 0, true),
('ROLE_UPDATE', 'Rol Güncelleme', 'Rol bilgilerini güncelleme yetkisi', 'ROLE_MANAGEMENT', true, 32, now(), now(), 0,
 true),
('ROLE_DELETE', 'Rol Silme', 'Rol silme yetkisi', 'ROLE_MANAGEMENT', true, 33, now(), now(), 0, true),
('ROLE_DEACTIVATE', 'Rol Pasifleştirme', 'Rolü pasif hale getirme yetkisi', 'ROLE_MANAGEMENT', true, 34, now(), now(),
 0, true),
('ROLE_ACTIVATE', 'Rol Aktifleştirme', 'Rolü aktif hale getirme yetkisi', 'ROLE_MANAGEMENT', true, 35, now(), now(), 0,
 true),
('ROLE_MANAGE', 'Rol Yönetimi', 'Genel rol yönetim yetkisi', 'ROLE_MANAGEMENT', true, 36, now(), now(), 0, true),
('ROLE_ASSIGN_PERMISSION', 'İzin Atama', 'Role izin atama yetkisi', 'ROLE_MANAGEMENT', true, 37, now(), now(), 0, true),
('ROLE_REVOKE_PERMISSION', 'İzin Geri Alma', 'Rolden izin geri alma yetkisi', 'ROLE_MANAGEMENT', true, 38, now(), now(),
 0, true),

-- Permission Management
('PERMISSION_VIEW', 'İzin Görüntüleme', 'Sistem izinlerini görüntüleme yetkisi', 'PERMISSION_MANAGEMENT', true, 40,
 now(), now(), 0, true),

-- Job Title Management
('JOB_TITLE_CREATE', 'Unvan Oluşturma', 'Yeni unvan oluşturma yetkisi', 'JOB_TITLE_MANAGEMENT', true, 50, now(), now(),
 0, true),
('JOB_TITLE_VIEW', 'Unvan Görüntüleme', 'Unvanları görüntüleme yetkisi', 'JOB_TITLE_MANAGEMENT', true, 51, now(), now(),
 0, true),
('JOB_TITLE_UPDATE', 'Unvan Güncelleme', 'Unvan bilgilerini güncelleme yetkisi', 'JOB_TITLE_MANAGEMENT', true, 52,
 now(), now(), 0, true),
('JOB_TITLE_DELETE', 'Unvan Silme', 'Unvan silme yetkisi', 'JOB_TITLE_MANAGEMENT', true, 53, now(), now(), 0, true),
('JOB_TITLE_DEACTIVATE', 'Unvan Pasifleştirme', 'Unvanı pasif hale getirme yetkisi', 'JOB_TITLE_MANAGEMENT', true, 54,
 now(), now(), 0, true),
('JOB_TITLE_ACTIVATE', 'Unvan Aktifleştirme', 'Unvanı aktif hale getirme yetkisi', 'JOB_TITLE_MANAGEMENT', true, 55,
 now(), now(), 0, true),
('JOB_TITLE_MANAGE', 'Unvan Yönetimi', 'Genel unvan yönetim yetkisi', 'JOB_TITLE_MANAGEMENT', true, 56, now(), now(), 0,
 true),
('JOB_TITLE_ASSIGN_DEFAULT_ROLE', 'Varsayılan Rol Atama', 'Unvana varsayılan rol atama yetkisi', 'JOB_TITLE_MANAGEMENT',
 true, 57, now(), now(), 0, true),
('JOB_TITLE_REMOVE_DEFAULT_ROLE', 'Varsayılan Rol Kaldırma', 'Unvandan varsayılan rol kaldırma yetkisi',
 'JOB_TITLE_MANAGEMENT', true, 58, now(), now(), 0, true),

-- Room Management
('ROOM_CREATE', 'Oda Oluşturma', 'Yeni toplantı odası oluşturma yetkisi', 'ROOM_MANAGEMENT', true, 60, now(), now(), 0,
 true),
('ROOM_VIEW', 'Oda Görüntüleme', 'Oda dolu/boş bilgisini görüntüleme yetkisi', 'ROOM_MANAGEMENT', true, 61, now(),
 now(), 0, true),
('ROOM_VIEW_AVAILABILITY', 'Oda Uygunluğu Görüntüleme', 'Oda takvim uygunluğunu görüntüleme yetkisi', 'ROOM_MANAGEMENT',
 true, 62, now(), now(), 0, true),
('ROOM_UPDATE', 'Oda Güncelleme', 'Oda bilgilerini güncelleme yetkisi', 'ROOM_MANAGEMENT', true, 63, now(), now(), 0,
 true),
('ROOM_DELETE', 'Oda Silme', 'Oda silme yetkisi', 'ROOM_MANAGEMENT', true, 64, now(), now(), 0, true),
('ROOM_DEACTIVATE', 'Oda Pasifleştirme', 'Odayı pasif hale getirme yetkisi', 'ROOM_MANAGEMENT', true, 65, now(), now(),
 0, true),
('ROOM_ACTIVATE', 'Oda Aktifleştirme', 'Odayı aktif hale getirme yetkisi', 'ROOM_MANAGEMENT', true, 66, now(), now(), 0,
 true),
('ROOM_MANAGE_FEATURES', 'Oda Özelliklerini Yönetme', 'Odaya özellik ekleme/kaldırma yetkisi', 'ROOM_MANAGEMENT', true,
 67, now(), now(), 0, true),

-- Feature Management
('FEATURE_CREATE', 'Özellik Oluşturma', 'Yeni oda özelliği oluşturma yetkisi', 'FEATURE_MANAGEMENT', true, 70, now(),
 now(), 0, true),
('FEATURE_VIEW', 'Özellik Görüntüleme', 'Oda özelliklerini görüntüleme yetkisi', 'FEATURE_MANAGEMENT', true, 71, now(),
 now(), 0, true),
('FEATURE_UPDATE', 'Özellik Güncelleme', 'Oda özelliğini güncelleme yetkisi', 'FEATURE_MANAGEMENT', true, 72, now(),
 now(), 0, true),
('FEATURE_DELETE', 'Özellik Silme', 'Oda özelliği silme yetkisi', 'FEATURE_MANAGEMENT', true, 73, now(), now(), 0,
 true),

-- Reservation Management
('RESERVATION_CREATE', 'Rezervasyon Oluşturma', 'Yeni rezervasyon oluşturma yetkisi', 'RESERVATION_MANAGEMENT', true,
 80, now(), now(), 0, true),
('RESERVATION_VIEW_OWN', 'Kendi Rezervasyonunu Görüntüleme', 'Kendi rezervasyonlarını görüntüleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 81, now(), now(), 0, true),
('RESERVATION_VIEW_ALL', 'Tüm Rezervasyonları Görüntüleme', 'Tüm rezervasyonları görüntüleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 82, now(), now(), 0, true),
('RESERVATION_UPDATE_OWN', 'Kendi Rezervasyonunu Güncelleme', 'Kendi rezervasyonunu güncelleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 83, now(), now(), 0, true),
('RESERVATION_UPDATE_ALL', 'Tüm Rezervasyonları Güncelleme', 'Tüm rezervasyonları güncelleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 84, now(), now(), 0, true),
('RESERVATION_CANCEL_OWN', 'Kendi Rezervasyonunu İptal Etme', 'Kendi rezervasyonunu iptal etme yetkisi',
 'RESERVATION_MANAGEMENT', true, 85, now(), now(), 0, true),
('RESERVATION_CANCEL_ALL', 'Tüm Rezervasyonları İptal Etme', 'Tüm rezervasyonları iptal etme yetkisi',
 'RESERVATION_MANAGEMENT', true, 86, now(), now(), 0, true),
('RESERVATION_APPROVE', 'Rezervasyon Onaylama', 'Bekleyen rezervasyonu onaylama yetkisi', 'RESERVATION_MANAGEMENT',
 true, 87, now(), now(), 0, true),
('RESERVATION_REJECT', 'Rezervasyon Reddetme', 'Bekleyen rezervasyonu reddetme yetkisi', 'RESERVATION_MANAGEMENT', true,
 88, now(), now(), 0, true),
('RESERVATION_VIEW_DETAILS', 'Rezervasyon Detayı Görüntüleme', 'Rezervasyon detaylarını görüntüleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 89, now(), now(), 0, true),
('RESERVATION_FILTER_BY_DATE', 'Tarihe Göre Filtreleme', 'Rezervasyonları tarihe göre filtreleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 90, now(), now(), 0, true),
('RESERVATION_FILTER_BY_ROOM', 'Odaya Göre Filtreleme', 'Rezervasyonları odaya göre filtreleme yetkisi',
 'RESERVATION_MANAGEMENT', true, 91, now(), now(), 0, true),

-- Visitor Management
('VISITOR_CREATE', 'Ziyaretçi Kaydı Oluşturma', 'Yeni ziyaretçi kaydı oluşturma yetkisi', 'VISITOR_MANAGEMENT', true,
 100, now(), now(), 0, true),
('VISITOR_VIEW', 'Ziyaretçi Görüntüleme', 'Ziyaretçi kayıtlarını görüntüleme yetkisi', 'VISITOR_MANAGEMENT', true, 101,
 now(), now(), 0, true),
('VISITOR_CHECK_IN', 'Ziyaretçi Giriş İşlemi', 'Ziyaretçiyi içeri alma yetkisi', 'VISITOR_MANAGEMENT', true, 102, now(),
 now(), 0, true),
('VISITOR_CHECK_OUT', 'Ziyaretçi Çıkış İşlemi', 'Ziyaretçi çıkış işlemi yapma yetkisi', 'VISITOR_MANAGEMENT', true, 103,
 now(), now(), 0, true),
('VISITOR_ASSIGN_CARD', 'Ziyaretçi Kart Verme', 'Ziyaretçiye kart numarası verme yetkisi', 'VISITOR_MANAGEMENT', true,
 104, now(), now(), 0, true),
('VISITOR_VIEW_HISTORY', 'Ziyaretçi Geçmişi Görüntüleme', 'Ziyaretçi geçmişini görüntüleme yetkisi',
 'VISITOR_MANAGEMENT', true, 105, now(), now(), 0, true),
('VISITOR_CANCEL', 'Ziyaretçi Kaydı İptal Etme', 'Ziyaretçi kaydını iptal etme yetkisi', 'VISITOR_MANAGEMENT', true,
 106, now(), now(), 0, true),

-- Dashboard
('DASHBOARD_VIEW', 'Panel Görüntüleme', 'Dashboard görüntüleme yetkisi', 'DASHBOARD', true, 110, now(), now(), 0, true),

-- Reports
('REPORT_VIEW_DAILY_VISITORS', 'Günlük Ziyaretçi Raporu', 'Günlük ziyaretçi listesini görüntüleme yetkisi', 'REPORTING',
 true, 120, now(), now(), 0, true),
('REPORT_VIEW_ACTIVE_VISITORS', 'Aktif Ziyaretçi Raporu', 'İçerideki aktif ziyaretçileri görüntüleme yetkisi',
 'REPORTING', true, 121, now(), now(), 0, true),
('REPORT_VIEW_UNCHECKED_OUT_VISITORS', 'Çıkış Yapmamış Ziyaretçi Raporu',
 'Çıkış yapmamış ziyaretçileri görüntüleme yetkisi', 'REPORTING', true, 122, now(), now(), 0, true),
('REPORT_VIEW_ROOM_USAGE', 'Oda Kullanım Raporu', 'Oda bazlı kullanım oranını görüntüleme yetkisi', 'REPORTING', true,
 123, now(), now(), 0, true),
('REPORT_VIEW_RESERVATION_STATS', 'Rezervasyon İstatistikleri',
 'Kullanıcı bazlı rezervasyon sayısını görüntüleme yetkisi', 'REPORTING', true, 124, now(), now(), 0, true),
('REPORT_VIEW_CANCELLATION_STATS', 'İptal İstatistikleri', 'İptal edilen rezervasyonları görüntüleme yetkisi',
 'REPORTING', true, 125, now(), now(), 0, true),
('REPORT_EXPORT_EXCEL', 'Excel Dışa Aktarma', 'Raporları Excel formatında dışa aktarma yetkisi', 'REPORTING', true, 126,
 now(), now(), 0, true),

-- Audit Log
('AUDIT_LOG_VIEW', 'Denetim Kaydı Görüntüleme', 'Audit log kayıtlarını görüntüleme yetkisi', 'AUDIT', true, 130, now(),
 now(), 0, true),

-- Notification
('NOTIFICATION_VIEW', 'Bildirim Görüntüleme', 'Bildirimleri görüntüleme yetkisi', 'NOTIFICATION', true, 140, now(),
 now(), 0, true),
('NOTIFICATION_MANAGE_SETTINGS', 'Bildirim Ayarlarını Yönetme', 'Bildirim ayarlarını yönetme yetkisi', 'NOTIFICATION',
 true, 141, now(), now(), 0, true);